---

- name: remove httpd if necessery (to prevent binding problems)
  yum:
    name: httpd
    state: absent

- name: NGINX | Installing NGINX repo rpm
  yum:
    name: http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
  become: true
  become_user: root
   
- name: Installing relevant packages
  yum: name={{ item }} state=installed
  with_items:
     - nginx
     - python-firewall 
     - firewalld
  become: true
  become_user: root

- name: upgrade all packages
  yum:
    name: '*'
    state: latest
  become: true
  become_user: root

- name: Create SSL directory
  file: 
    path: /etc/nginx/ssl
    state: directory
    mode: 0644

- name: copy CERTS for SSL
  copy:
    src: "{{ item }}"
    dest: /etc/nginx/ssl
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_items: 
     - "files/server.crt"
     - "files/server.key" 
 
- name: overwrite nginx.conf
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: copy index.html
  copy:
    src: files/index.html
    dest: /usr/share/nginx/html
    owner: root
    group: root
    mode: 0644
    backup: yes

- name : Enable and start nginx service 
  service: name=nginx state=started enabled=True
  become: true
  become_user: root
  
- name: Configure firewalld
  firewalld:
     service: "{{ item.service }}"
     permanent: "{{ item.permanent }}"
     state: enabled
  with_items:
    - { service: 'ssh', permanent: true }
    - { service: 'http', permanent: true }
    - { service: 'https', permanent: true }
  become: true
  become_user: root
  
